---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhomeapigw
  namespace: zhomeapigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zhomeapigw
  template:
    metadata:
      labels:
        app: zhomeapigw
    spec:
      containers:
        - name: zhomeapigw
          image: zxyxy/zhomeapigw:0.1.0
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: zhomeapigw
  namespace: zhomeapigw
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: zhomeapigw

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zhomeapigw
  namespace: zhomeapigw
spec:
  rules:
    - host: api.zxyxyhome.duckdns.org
      http:
        paths:
          - backend:
              service:
                name: zhomeapigw
                port:
                  number: 80
            path: /
            pathType: Prefix
