kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
  namespace: monitoring
  data:
    prometheus.yml: |
      - job_name: 'freya_monitor'
        static_configs:
        - targets: ['172.21.0.2:9100']
