apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud
spec:
  capacity:
    storage: 2500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /storage01/kube/nextcloud
    server: 172.21.0.2
