apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins
  mountOptions:
    - hard
    - nfsvers=4.1
  local:
    path: /storage01/kube/jenkins
#    server: 172.21.0.2
