apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins
  mountOptions:
    - hard
    - nfsvers=4.1
#    - rw
#    - bg
    - rsize=32768
    - wsize=32768
#    - tcp
#    - timeo=600
    - no_subtree_check
  nfs:
    path: /storage01/kube/jenkins
    server: 172.21.0.2
