apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins
#  nodeAffinity: Local
#  mountOptions:
#    - hard
 #   - nfsvers=4.1
  local:
    path: /srv/kubernetes/jenkins
#    server: 172.21.0.2
