apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins
#  nodeAffinity: Local
#  mountOptions:
#    - hard
 #   - nfsvers=4.1
  local:
    path: /srv/kubernetes/jenkins
#    server: 172.21.0.2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-z-agent-0
          - k3d-z-agent-1
          - k3d-z-agent-2
