apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: influxdb
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /storage01/kube/influxdb
    server: 172.21.0.2
