---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: influxdb
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /storage01/kube/influxdb
    server: 172.21.0.2

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: influxdb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.4.19
    helm:
      releaseName: influxdb
      parameters:
      - name: persistence.storageClass
        value: influxdb
      - name: persistence.size
        value: 100Gi
      - name: persistence.enabled
        value: "true"
      - name: volumePermissions.enabled
        value: "false"
      values: |
        ingress:
          enabled: true
          hostname: influxdb.db.zxyxyhome.duckdns.org
        auth:
          username: admin
          password: admin
        influxdb:
          startupProbe:
            enabled: true
            initialDelaySeconds: 360
            periodSeconds: 45
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 6
  destination:
    namespace: influxdb
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
