apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 250Gi
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /storage02/kube/torrent-z/toDownload/
    server: 172.21.0.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: torrent-z-xml-files
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filespv
  namespace: torrent-z
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: torrent-z-xml-files
  volumeMode: Filesystem
