apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-loki
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-loki
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /storage01/kube/grafana-loki
    server: 172.21.0.2
