apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /storage01/kube/grafana
    server: 172.21.0.2
