apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: influxdb
    repoURL: https://helm.influxdata.com
    targetRevision: 4.12.1
    helm:
      releaseName: influxdb
      parameters:
      - name: persistence.storageClass
        value: influxdb
      values: |
        ingress:
          enable: true
          hostname: influxdb.db.zxyxyhome.duckdns.org
  destination:
    namespace: influxdb
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
