apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mosquitto
    repoURL: https://sintef.github.io/mosquitto-helm-chart
    targetRevision: 0.1.0
    helm:
      releaseName: mosquitto
      parameters:
#      - name: auth.users[0].password
#        value: "$7$101$7yMhV1zPLAAcV9f8$02zO+X4eGuI0N+H5XY6tgUye2l+eKp4QffV1ZaJtJ15mUyCSxgWpwAqLS2CCXSzpnCSqRrPMi2sa7PdzAKMI1w=="
#      - name: auth.users[0].username
#        value: admin
      values: |
        service:
          type: LoadBalancer
        auth:
          enabled: true
          users:
            - username: admin
              password: $6$BD2qkjJO.fur4/vG$DsIjDm2ux9bJKHXcfGmfWbcvNcRvH24zwxAxKbvUlw3KNLIjlS7eVU/.DJ2HJXo3fjSfPUyanzc7hskws7OxF0
              acl:
                - topic: "#"
                  access: readwrite
  destination:
    namespace: mqtt
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
