apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /storage01/kube/postgres
    server: 172.21.0.2
