apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.1.5
    helm:
      releaseName: postgresql
      parameters:
      - name: primary.persistence.enabled
        value: "true"
      - name: global.storageClass
        value: postgres
      - name: primary.persistence.size
        value: "100Gi"
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
