apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /storage02/kube/torrent-z/xmldb
    server: 172.21.0.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: torrent-z-xml-db
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbpv
  namespace: torrent-z
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: torrent-z-xml-db
  volumeMode: Filesystem
